### ISSUE TITLE
Rework "times of day" for more accurate greetings

### ISSUE THREAD

**Issue by spacekookie** [AlexanderOtavka/clean-tab#19] opened 2017-03-21 23:54 UTC
Right now it's

Midnight - Noon  = Morning
Noon - ~18:00 = Afternoon
~18:00 - Midnight = Evening

What would be a lot cooler (imo) is something like this

06:00 - 12:00 = Morning
12:00 - 18:00 = Afternoon
18:00 - 11:00 = Evening
11:00 - 06:00 (next day) = Night

Because it just ticked over to the new day and squaretabs is telling me "Good morning" and I'm about to go sleep 😝

**Comment by AlexanderOtavka** [comment] 2017-03-31 22:36
Hi, sorry I couldn't get back to you sooner; I was out of town for the past week and a half.

Right now, it is behaving as intended.  The message is meant to be a greeting and — at least in my mind — "Good Night" is a goodbye.  For example, if I was walking late at night and I came across someone, I would say "Good Evening" or if it was close enough to morning, I would say "Good Morning."

However, I'm with you that for certain hours of the night, neither really feels appropriate.  There is an [interesting discussion](http://english.stackexchange.com/questions/100870/what-is-an-appropriate-greeting-to-use-at-night-time) on StackExchange around this.  One commenter makes a suggestion I like, which is to simply abandon the "Good [time of day]" pattern and go with something like "Greetings, Night Owl" or ["Hello There"](https://media1.giphy.com/media/KOVlHmbBA09XO/giphy.gif).  I like that it is sort of an easter egg for those of us up late.

What are your thoughts?  I'm going to hold off merging #21 until we figure this out.

**Comment by duncangrubbs** [comment] 2017-03-31 23:20
I agree with both of you on the idea that after midnight it certainly shouldn't say 'Good Morning'. I also agree with Zander that 'Good Night' sounds like you are saying goodbye. Possibly something like "Greetings" or "Hello There".

**Comment by AlexanderOtavka** [comment] 2017-04-01 00:30
In my latest commit, I'm going with "Hello, Night Owl."  We can test it in the dev build and see how it feels.

**Comment by spacekookie** [comment] 2017-04-01 11:39
"Greetings, Night Owl" sounds like an awesome greeting, yea :)

**Comment by AlexanderOtavka** [comment] 2017-04-11 00:57
The fix has been released.

**Closed as completed by AlexanderOtavka** 2017-04-11 00:57 UTC
